# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:


- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/AzFnArmTemplate'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/AzFnArmTemplate'
    OverWrite: true/
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: 'drop'

    
- script: |
    dotnet restore
    dotnet build --configuration Release
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '--configuration Release --output publish_output'
    projects: '**/*.csproj'
    publishWebProjects: false
    modifyOutputPath: true
    zipAfterPublish: false
- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output/AzFnFileService"
    includeRootFolder: false
    archiveFile: "$(System.DefaultWorkingDirectory)/AzFnFileService/AzFnFileService.zip"
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'AzFnFileService/AzFnFileService.zip'
    name: 'drop'

